name: Publish Documentation

on:
  push:
    branches:
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Unity references
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Updated to match your error log version

      # Install DocFX
      - name: Install DocFX
        run: dotnet tool update -g docfx

      # Copy README as index (using bash)
      - name: Copy README as index
        run: cp README.md docs/index.md
        shell: bash

      # Add Unity references to DocFX metadata
      - name: Update DocFX config
        run: |
          echo '{"sdk": {"version": "8.0.0"}, "msbuild": {"properties": {"UnityVersion": "6000.0"}}}' > docs/docfx.json.unity
          cat docs/docfx.json.unity docs/docfx.json > docs/docfx.json.tmp
          mv docs/docfx.json.tmp docs/docfx.json
        shell: bash

      # Build documentation
      - name: Build Documentation
        run: docfx docs/docfx.json
        env:
          DOTNET_ROOT: /usr/share/dotnet

      # Create .nojekyll (using bash)
      - name: Create .nojekyll
        run: touch docs/_site/.nojekyll
        shell: bash

      - name: List deployed files
        run: ls -la docs/_site
        shell: bash

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: docs/_site

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4