name: Build and Deploy Documentation

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install DocFX
        run: choco install -y docfx

      - name: Install wkhtmltopdf
        run: |
          choco install wkhtmltopdf --version=0.12.6 -y
          $env:Path = "C:\Program Files\wkhtmltopdf\bin;$env:Path"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
          wkhtmltopdf --version
        shell: powershell

      - name: Use README.md as index.md
        run: copy README.md Documentation\index.md
        shell: cmd

      - name: Clean previous builds
        run: |
          cd Documentation
          Remove-Item -Path _site -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path obj -Recurse -Force -ErrorAction SilentlyContinue
        shell: powershell

      - name: Generate Metadata
        run: |
          cd Documentation
          docfx metadata
        shell: cmd

      - name: Generate PDF
        run: |
          cd Documentation
          docfx pdf
        shell: cmd

      - name: Build Documentation
        run: |
          cd Documentation
          docfx build
        shell: cmd

      - name: Verify PDF Generation
        run: |
          cd Documentation
          if (Test-Path "_site/_pdf/Documentation_api.pdf") {
              Write-Host "PDF files generated successfully"
          } else {
              Write-Host "Warning: PDF files not found in expected location"
              exit 1
          }
        shell: powershell

      - name: Create .nojekyll file
        run: type nul > Documentation/_site/.nojekyll
        shell: cmd
        
      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: Documentation/_site

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation_pdfs
          path: Documentation/_site/_pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: _site
          path: _site

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation_pdfs
          path: _site/_pdf

      - name: Create .nojekyll file
        run: touch _site/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site