name: Build and Deploy Documentation

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install DocFX
        run: choco install -y docfx

      - name: Install wkhtmltopdf
        run: choco install -y wkhtmltopdf

      - name: Debug Project Structure
        run: |
          echo "Current directory structure:"
          dir /s /b
          echo "Looking for C# files:"
          dir /s /b *.cs
        shell: cmd
        continue-on-error: true

      - name: Use README.md as index.md
        run: copy README.md Documentation\index.md
        shell: cmd

      - name: Generate Metadata
        run: |
          cd Documentation
          echo "Current directory:"
          cd
          echo "Content of current directory:"
          dir
          echo "Generating metadata with docfx.json..."
          docfx metadata docfx.json --force
          echo "Checking generated files:"
          dir /s /b api
        shell: cmd

      - name: Build Documentation
        run: |
          cd Documentation
          docfx build docfx.json --force
        shell: cmd

      - name: Create PDF directory
        run: New-Item -ItemType Directory -Force -Path Documentation\_site\_pdf
        shell: powershell

      - name: Generate PDFs
        run: |
          cd Documentation/_site
          
          Write-Host "Checking API documentation..."
          if (Test-Path "api/Global.html") {
              Write-Host "API documentation exists, using Global.html as entry point"
              $apiEntryPoint = "api/Global.html"
          } else {
              Write-Host "Warning: API documentation not found!"
              Write-Host "Directory content:"
              Get-ChildItem -Recurse | Select-Object FullName
              exit 1
          }
          
           $serverProcess = Start-Process docfx -ArgumentList "serve", "." -PassThru -WindowStyle Hidden
          Start-Sleep -Seconds 20
          
          Write-Host "Generating API PDF..."
          wkhtmltopdf --enable-local-file-access `
                     --print-media-type `
                     --javascript-delay 5000 `
                     --no-stop-slow-scripts `
                     --debug-javascript `
                     --load-error-handling ignore `
                     --load-media-error-handling ignore `
                     http://localhost:8080/$apiEntryPoint "_pdf/Documentation_api.pdf"
          
          Write-Host "Generating main documentation PDF..."
          wkhtmltopdf --enable-local-file-access `
                     --print-media-type `
                     --javascript-delay 5000 `
                     --no-stop-slow-scripts `
                     --debug-javascript `
                     --load-error-handling ignore `
                     --load-media-error-handling ignore `
                     http://localhost:8080/index.html "_pdf/Documentation.pdf"
          
          Stop-Process -Id $serverProcess.Id
          
          Write-Host "Checking generated PDFs:"
          Get-ChildItem "_pdf" | ForEach-Object {
              Write-Host "$($_.Name): $($_.Length) bytes"
          }
        shell: powershell

      - name: Create .nojekyll file
        run: type nul > Documentation/_site/.nojekyll
        shell: cmd

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: Documentation/_site

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation_pdfs
          path: Documentation/_site/_pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: _site
          path: _site

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation_pdfs
          path: _site/_pdf

      - name: Create .nojekyll file
        run: touch _site/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site